ss_blog/urls.py
from django.urls import path
from ss_blog.views import home_view,edit_my_model,add_article,contentpage_view,post_comment,loging,delete_post

app_name='ss_blog'

urlpatterns = [
    path('',home_view,name='home'),
    path('home',home_view),
    path('add',add_article,name='add-article'),
    path('<int:Topics_id>/comment',post_comment,name='post_comment'),
    path('log_reg',loging,name='log_reg_template'),

    path('article/<int:Topics_id>',contentpage_view,name='contentpage_view'),
    path('article/<int:Article_id>/edit',edit_my_model,name='edit'),
    path('article/<int:Article_id>/delete/', delete_post, name='delete_post'),
]

ss_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ss_blog.urls',namespace='ss_blog')) # new
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ss_blog/models.py
from django.db import models

# Create your models here.

class Topics(models.Model):
    topic_name=models.CharField(max_length=200)

    def __str__(self):
        return self.topic_name
    
class Article(models.Model):
    topic=models.ForeignKey(Topics,on_delete=models.CASCADE,related_name='articles')
    tittle= models.CharField(max_length=200)
    article=models.TextField()
    created_at=models.DateTimeField(auto_now=True)
    image_name=models.CharField(max_length=100)
    image=models.ImageField(upload_to='pics/')
    def __str__(self):
        return self.tittle


class Comment(models.Model):
    post = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=100)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

ss_blog/forms.py
from django import forms
from .models import Topics,Article,Comment
      
class Topic_form(forms.ModelForm):
    class Meta():
        model=Topics
        fields=("topic_name",) 
         
class Article_form(forms.ModelForm):
    class Meta():
        model=Article
        exclude=["created_at",]

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text')

ss_blog/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Topics,Article,Comment
from .forms import Article_form,CommentForm
# Create your views here.

def add_article(request):
    if request.method == 'POST':
        form = Article_form(request.POST, request.FILES)
        if form.is_valid():
            # Save the form data to the database
            article = form.save(commit=False)
            article.save()
            return redirect('ss_blog:home')
        else:
            # Display the form with validation errors
            print(form.errors)
            return render(request, 'ss_blog/add_article.html', {'form': form})
    else:
        # Display a blank form for adding a new article
        form = Article_form()
        return render(request, 'ss_blog/add_article.html', {'form': form})

def home_view(request):
    topic_na=Article.objects.all()
    return render(request,'ss_blog/home.html',{'topic_na':topic_na,})

def contentpage_view(request, Topics_id):
    post = get_object_or_404(Article, id=Topics_id)
    comments = Comment.objects.filter(post=post)
    form = CommentForm(initial={'post': post})
    return render(request, 'ss_blog/display_content_page.html', {'post': post, 'comments': comments, 'form': form})

def post_comment(request,Topics_id):
    post=get_object_or_404(Article,id=Topics_id)
    if request.method =='POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=post
            comment.save()
            return redirect('ss_blog:contentpage_view',Topics_id=post.id)
    else:
        form =CommentForm(initial={'post':post})
    return render(request,'ss_blog/display_content_page.html',{'post':post,'form':form,})


    

def loging(request):
    post = Article.objects.all()
    return render(request,'ss_blog/login.html',{' post':post})

def edit_my_model(request,Article_id):
    post = get_object_or_404(Article, id=Article_id)
    if request.method == 'POST':
        form =Article_form(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('ss_blog:contentpage_view', Topics_id=post.id)
    else:
        form = Article_form(instance=post)
    return render(request, 'ss_blog/edit.html', {'form': form, 'post': post})


def delete_post(request, Article_id):
    post = get_object_or_404(Article, id=Article_id)
    if request.method == 'POST':
        post.delete()
        return redirect('ss_blog:home')  # Redirect to the home view after deletion
    return render(request, 'ss_blog/delete.html', {'post': post})

templates/ss_blog/add_article.html
{% extends 'ss_blog/base.html' %}
{% block content %}
<div class="content_container">
    <h1>Add article</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" name="button"class="btn-primary">submit</button>
    </form>
</div>
{% endblock %}

templates/ss_blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- css files links-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <link rel="stylesheet" href="{% static 'css/style1.css'%}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <title>{% block title %} ss blog {% endblock %}</title>
</head>
<body>
    <div class="heading"><h1>ss-news  blog</h1></div>
    <header>
        <div class="logo"><h2>Logo</h2></div>
        <nav class="navigation">
            <a href="{% url 'ss_blog:home'%}">Home</a>
            <a href="{% url 'ss_blog:add-article'%}">Add articles</a>
            <a href="#about">About</a>
            <a href="{% url 'ss_blog:log_reg_template'%}" class="btnLogin-popup">Login</a>
        </nav>
    </header>
    {% block content %}
    {% endblock %}
</body>
<!--java script links-->
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
</html>

templates/ss_blog/delete.html
{% extends 'ss_blog/edit.html' %}

{% block content %}
<div class="con_delete">
  <h1>Delete Article</h1>
  <p>Are you sure you want to delete "{{ post.topic }}"?</p>
  <form method="POST" action="{% url 'ss_blog:delete_post' post.id %}">
    {% csrf_token %}
    <div class="btn1">
      <button type="submit" class="closed_c">Delete</button>
    </div>
    <div class="display_image" style="  display: flex;
    justify-content: center;
    align-content: center;"><img src={{post.image.url}} alt=""></div>
  </form>
  <div class="close" style="
  display: flex;
  justify-content: center;
  align-content: center; 
  margin-top: 10px; 
  "><a href="{% url 'ss_blog:contentpage_view' post.id %}" class="closed_c">close</a></div>
  
</div>

{% endblock %}

templates/ss_blog/display_content_page.html
{% extends 'ss_blog/base.html' %}
{% block content %}
<div class="container-sub">
    <div class="sub_content">
        <div class="sub-heading">
            <h3>{{post.tittle}}</h3>
        </div>
        <div class="text">
            <div class="picture">
                <div class="display_image"><img src={{post.image.url}} alt=""></div>
                <h3 class="head_comments">comments</h3>
                <div class="comments">
                    <div class="comment_paragraph">
                        {% if comments %}
                        <div>
                            {% for comment in comments %}
                            <div class="comment_per">
                                <h2 class="user_name">{{ comment.author }}</h2>
                                <p class="comment"> {{ comment.text }}</p>
                                <p class="dateC">{{comment.created_date}}</p>
                            </div>
                          
                            {% endfor %}
                        </div>
                        {% else %}
                        <p>No comments yet.</p>
                        {% endif %}
                    </div>
                </div>
                <h3 class="addC_">Add comment</h3>
                <form method="post" class="comment_input" action="{% url 'ss_blog:post_comment' Topics_id=post.id %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Submit</button>
                </form>                             
            </div>
            <div class="para_3">
                <p class="">{{post.article}}</p>
                <h5>{{post.created_at}}</h5>
                <div class="edit">
                    <a href="{% url 'ss_blog:edit' post.id %}">edit article</a>
                </div> 
                <div class="delete1">
                    <a href="{% url 'ss_blog:delete_post' post.id %}" style="border: none;">delete article</a>
                </div>  
              
            </div>

        </div>  
    </div>
</div>
{% endblock %}

templates/ss_blog/edit.html
{% extends 'ss_blog/base.html' %}
{% block content %}
<div class="content_container">
    <h1></h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" name="button" class="btn-primary">save changes</button>
    </form>
</div>
{% endblock %}

templates/ss_blog/home.html
{% extends 'ss_blog/base.html' %}
{% block content %}
<div class="content_container">
    <div class="grid">
        {% for x in topic_na %}
        <div class="n1">
            <a href="{% url 'ss_blog:contentpage_view' x.id %}">
                <img src="{{ x.image.url }}" alt="Lights">
            </a>
        <p class="navigation"><a href="{% url 'ss_blog:contentpage_view' x.id %}">{{x.topic}}</a></p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/ss_blog/login.html
{% extends 'ss_blog/base.html' %}
{% block content %}
<div class="wrapper2">
    <div class="wrapper">
        <!--close icon-->
        <a href="{% url 'ss_blog:home' %}"><span class="close_icon" ><ion-icon name="close"></ion-icon></span>
        </a>
  
        <!--loging form-->
        <div class="form-login">
            <h2>Login</h2>
            <div class="input-box">
                <span class="icon-inputs"><ion-icon name="mail"></ion-icon></span>
                <input type="text" required>
                <label>Email</label>
            </div>
            <div class="input-box">
                <span class="icon-inputs"><ion-icon name="lock-closed"></ion-icon></span>
                <input type="password" required>
                <label>Password</label>
            </div>
            <div class="remember-forgot">
                <label>
                    <input type="checkbox" class="input-check">
                    Remember me
                </label>
                <a href="#">Forgot Password?</a>
            </div>
            <button type="submit" class="submit-class">Login</button>
            <div class="no-acccount">
                <label >Don't have an account?</label>
                <a href="#" class="register-link">Register</a>
            </div>
        </div>
        <!--regiter form-->
        <div class="form-register">
            <h2>Registration</h2>
            <div class="input-box">
                <span class="icon-inputs"><ion-icon name="person"></ion-icon></span>
                <input type="text" required>
                <label>Username</label>
            </div>
            <div class="input-box">
                <span class="icon-inputs"><ion-icon name="mail"></ion-icon></span>
                <input type="text" required>
                <label>Email</label>
            </div>
            <div class="input-box">
                <span class="icon-inputs"><ion-icon name="lock-closed"></ion-icon></span>
                <input type="password" required>
                <label>Password</label>
            </div>
            <div class="remember-forgot">
                <label>
                    <input type="checkbox" class="input-check">
                    I agree to the terms & conditions
                </label>
            </div>
            <button type="submit" class="submit-class">Register</button>
            <div class="no-acccount">
                <label >Alredy have an account? </label>
                <a href="#" class="login-link">Login</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}